Response(
    id="resp_06655dbfaf2d45d300690ca9ada5388193b0278477b1358ffd",
    created_at=1762437550.0,
    error=None,
    incomplete_details=None,
    instructions=None,
    metadata={},
    model="gpt-5-2025-08-07",
    object="response",
    output=[
        ResponseReasoningItem(
            id="rs_06655dbfaf2d45d300690ca9b2daec81939de477189be8d792",
            summary=[],
            type="reasoning",
            content=None,
            encrypted_content=None,
            status=None,
        ),
        ResponseFunctionToolCall(
            arguments='{"conversation_id":"c40803b6-529d-4bea-aac6-5beea311f794","body_id":"ground","position_m":[0,0],"size_m":[24,0.2],"body_type":"static","angle_rad":0,"mass_kg":null,"friction":0,"restitution":0,"density_kg_m3":null,"notes":"frictionless horizontal surface"}',
            call_id="call_4c2FViFZ9NEKn5Gf6AUJ6JLx",
            name="create_block",
            type="function_call",
            id="fc_06655dbfaf2d45d300690ca9c7287c8193b28791164ad46c13",
            status="completed",
        ),
        ResponseFunctionToolCall(
            arguments='{"conversation_id":"c40803b6-529d-4bea-aac6-5beea311f794","body_id":"A","position_m":[-6,0.6],"size_m":[0.8,0.8],"body_type":"dynamic","angle_rad":0,"mass_kg":null,"friction":0,"restitution":0,"density_kg_m3":null,"notes":"Block A: mass M, momentum 3p to +x"}',
            call_id="call_Un6wwpYcNJshZqX6EYvY1sEG",
            name="create_block",
            type="function_call",
            id="fc_06655dbfaf2d45d300690ca9c8176481938a1b386da0a5049e",
            status="completed",
        ),
        ResponseFunctionToolCall(
            arguments='{"conversation_id":"c40803b6-529d-4bea-aac6-5beea311f794","body_id":"B","position_m":[-2,0.6],"size_m":[0.8,0.8],"body_type":"dynamic","angle_rad":0,"mass_kg":null,"friction":0,"restitution":0,"density_kg_m3":null,"notes":"Block B: mass m, momentum p to +x"}',
            call_id="call_QFJ73XJMol4u9znZvWYwICLe",
            name="create_block",
            type="function_call",
            id="fc_06655dbfaf2d45d300690ca9c940808193bdf45bae511a9509",
            status="completed",
        ),
        ResponseFunctionToolCall(
            arguments='{"conversation_id":"c40803b6-529d-4bea-aac6-5beea311f794","body_id":"C","position_m":[4,0.6],"size_m":[0.8,0.8],"body_type":"dynamic","angle_rad":0,"mass_kg":null,"friction":0,"restitution":0,"density_kg_m3":null,"notes":"Block C: mass 2m, momentum 4p to -x"}',
            call_id="call_eeiCe2Hj5uWiggQCcIMHIpCD",
            name="create_block",
            type="function_call",
            id="fc_06655dbfaf2d45d300690ca9ca7e108193a675b5a20264a208",
            status="completed",
        ),
    ],
    parallel_tool_calls=True,
    temperature=1.0,
    tool_choice="auto",
    tools=[
        FunctionTool(
            name="create_block",
            parameters={
                "type": "object",
                "properties": {
                    "conversation_id": {"title": "Conversation Id", "type": "string"},
                    "body_id": {
                        "anyOf": [{"type": "string"}, {"type": "null"}],
                        "description": "Optional explicit id",
                        "title": "Body Id",
                    },
                    "position_m": {
                        "maxItems": 2,
                        "minItems": 2,
                        "title": "Position M",
                        "type": "array",
                        "items": {"type": "number"},
                    },
                    "size_m": {
                        "maxItems": 2,
                        "minItems": 2,
                        "title": "Size M",
                        "type": "array",
                        "items": {"type": "number"},
                    },
                    "body_type": {
                        "default": "dynamic",
                        "enum": ["dynamic", "static", "kinematic"],
                        "title": "Body Type",
                        "type": "string",
                    },
                    "angle_rad": {
                        "anyOf": [{"type": "number"}, {"type": "null"}],
                        "description": "Rotation angle in radians",
                        "title": "Angle Rad",
                    },
                    "mass_kg": {
                        "anyOf": [{"type": "number"}, {"type": "null"}],
                        "title": "Mass Kg",
                    },
                    "friction": {
                        "anyOf": [{"type": "number"}, {"type": "null"}],
                        "title": "Friction",
                    },
                    "restitution": {
                        "anyOf": [{"type": "number"}, {"type": "null"}],
                        "title": "Restitution",
                    },
                    "density_kg_m3": {
                        "anyOf": [{"type": "number"}, {"type": "null"}],
                        "title": "Density Kg M3",
                    },
                    "notes": {
                        "anyOf": [{"type": "string"}, {"type": "null"}],
                        "title": "Notes",
                    },
                },
                "required": [
                    "conversation_id",
                    "body_id",
                    "position_m",
                    "size_m",
                    "body_type",
                    "angle_rad",
                    "mass_kg",
                    "friction",
                    "restitution",
                    "density_kg_m3",
                    "notes",
                ],
                "additionalProperties": False,
            },
            strict=True,
            type="function",
            description="Create a rectangular body. Use body_type='static' for surfaces.",
        ),
        FunctionTool(
            name="modify_block",
            parameters={
                "type": "object",
                "properties": {
                    "conversation_id": {"title": "Conversation Id", "type": "string"},
                    "body_id": {"title": "Body Id", "type": "string"},
                    "position_m": {
                        "anyOf": [
                            {
                                "maxItems": 2,
                                "minItems": 2,
                                "type": "array",
                                "items": {"type": "number"},
                            },
                            {"type": "null"},
                        ],
                        "title": "Position M",
                    },
                    "size_m": {
                        "anyOf": [
                            {
                                "maxItems": 2,
                                "minItems": 2,
                                "type": "array",
                                "items": {"type": "number"},
                            },
                            {"type": "null"},
                        ],
                        "title": "Size M",
                    },
                    "body_type": {
                        "anyOf": [
                            {
                                "enum": ["dynamic", "static", "kinematic"],
                                "type": "string",
                            },
                            {"type": "null"},
                        ],
                        "title": "Body Type",
                    },
                    "angle_rad": {
                        "anyOf": [{"type": "number"}, {"type": "null"}],
                        "title": "Angle Rad",
                    },
                    "mass_kg": {
                        "anyOf": [{"type": "number"}, {"type": "null"}],
                        "title": "Mass Kg",
                    },
                    "friction": {
                        "anyOf": [{"type": "number"}, {"type": "null"}],
                        "title": "Friction",
                    },
                    "restitution": {
                        "anyOf": [{"type": "number"}, {"type": "null"}],
                        "title": "Restitution",
                    },
                    "density_kg_m3": {
                        "anyOf": [{"type": "number"}, {"type": "null"}],
                        "title": "Density Kg M3",
                    },
                    "notes": {
                        "anyOf": [{"type": "string"}, {"type": "null"}],
                        "title": "Notes",
                    },
                },
                "required": [
                    "conversation_id",
                    "body_id",
                    "position_m",
                    "size_m",
                    "body_type",
                    "angle_rad",
                    "mass_kg",
                    "friction",
                    "restitution",
                    "density_kg_m3",
                    "notes",
                ],
                "additionalProperties": False,
            },
            strict=True,
            type="function",
            description="Update block position, size, material, or type for an existing body.",
        ),
        FunctionTool(
            name="remove_block",
            parameters={
                "type": "object",
                "properties": {
                    "conversation_id": {"title": "Conversation Id", "type": "string"},
                    "body_id": {"title": "Body Id", "type": "string"},
                },
                "required": ["conversation_id", "body_id"],
                "additionalProperties": False,
            },
            strict=True,
            type="function",
            description="Delete a block body from the scene by id.",
        ),
        FunctionTool(
            name="create_pulley",
            parameters={
                "type": "object",
                "properties": {
                    "conversation_id": {"title": "Conversation Id", "type": "string"},
                    "pulley_id": {
                        "anyOf": [{"type": "string"}, {"type": "null"}],
                        "title": "Pulley Id",
                    },
                    "center_m": {
                        "maxItems": 2,
                        "minItems": 2,
                        "title": "Center M",
                        "type": "array",
                        "items": {"type": "number"},
                    },
                    "radius_m": {
                        "exclusiveMinimum": 0.0,
                        "title": "Radius M",
                        "type": "number",
                    },
                    "axle_radius_m": {
                        "anyOf": [{"type": "number"}, {"type": "null"}],
                        "description": "Optional visual axle radius",
                        "title": "Axle Radius M",
                    },
                    "axle_body_id": {
                        "anyOf": [{"type": "string"}, {"type": "null"}],
                        "title": "Axle Body Id",
                    },
                    "notes": {
                        "anyOf": [{"type": "string"}, {"type": "null"}],
                        "title": "Notes",
                    },
                },
                "required": [
                    "conversation_id",
                    "pulley_id",
                    "center_m",
                    "radius_m",
                    "axle_radius_m",
                    "axle_body_id",
                    "notes",
                ],
                "additionalProperties": False,
            },
            strict=True,
            type="function",
            description="Create a pulley body (and optional axle) at the given position with radius in meters.",
        ),
        FunctionTool(
            name="create_rope",
            parameters={
                "type": "object",
                "properties": {
                    "conversation_id": {"title": "Conversation Id", "type": "string"},
                    "constraint_id": {
                        "anyOf": [{"type": "string"}, {"type": "null"}],
                        "title": "Constraint Id",
                    },
                    "body_a": {"title": "Body A", "type": "string"},
                    "body_b": {"title": "Body B", "type": "string"},
                    "anchor_a_m": {
                        "anyOf": [
                            {
                                "maxItems": 2,
                                "minItems": 2,
                                "type": "array",
                                "items": {"type": "number"},
                            },
                            {"type": "null"},
                        ],
                        "description": "Anchor offset on body A",
                        "title": "Anchor A M",
                    },
                    "anchor_b_m": {
                        "anyOf": [
                            {
                                "maxItems": 2,
                                "minItems": 2,
                                "type": "array",
                                "items": {"type": "number"},
                            },
                            {"type": "null"},
                        ],
                        "description": "Anchor offset on body B",
                        "title": "Anchor B M",
                    },
                    "length_m": {
                        "anyOf": [{"minimum": 0.0, "type": "number"}, {"type": "null"}],
                        "title": "Length M",
                    },
                    "stiffness": {
                        "anyOf": [{"minimum": 0.0, "type": "number"}, {"type": "null"}],
                        "title": "Stiffness",
                    },
                    "damping": {
                        "anyOf": [{"minimum": 0.0, "type": "number"}, {"type": "null"}],
                        "title": "Damping",
                    },
                    "notes": {
                        "anyOf": [{"type": "string"}, {"type": "null"}],
                        "title": "Notes",
                    },
                },
                "required": [
                    "conversation_id",
                    "constraint_id",
                    "body_a",
                    "body_b",
                    "anchor_a_m",
                    "anchor_b_m",
                    "length_m",
                    "stiffness",
                    "damping",
                    "notes",
                ],
                "additionalProperties": False,
            },
            strict=True,
            type="function",
            description="Add a rope constraint between two bodies with optional anchors and length.",
        ),
        FunctionTool(
            name="set_world",
            parameters={
                "type": "object",
                "properties": {
                    "conversation_id": {"title": "Conversation Id", "type": "string"},
                    "gravity_m_s2": {"title": "Gravity M S2", "type": "number"},
                    "time_step_s": {"title": "Time Step S", "type": "number"},
                },
                "required": ["conversation_id", "gravity_m_s2", "time_step_s"],
                "additionalProperties": False,
            },
            strict=True,
            type="function",
            description="Configure gravity and time step for the scene.",
        ),
        FunctionTool(
            name="set_mapping",
            parameters={
                "type": "object",
                "properties": {
                    "conversation_id": {"title": "Conversation Id", "type": "string"},
                    "origin_px": {
                        "maxItems": 2,
                        "minItems": 2,
                        "title": "Origin Px",
                        "type": "array",
                        "items": {"type": "number"},
                    },
                    "scale_m_per_px": {
                        "exclusiveMinimum": 0.0,
                        "title": "Scale M Per Px",
                        "type": "number",
                    },
                },
                "required": ["conversation_id", "origin_px", "scale_m_per_px"],
                "additionalProperties": False,
            },
            strict=True,
            type="function",
            description="Set pixel-to-meter mapping using origin_px and scale_m_per_px.",
        ),
    ],
    top_p=1.0,
    background=False,
    conversation=None,
    max_output_tokens=None,
    max_tool_calls=None,
    previous_response_id=None,
    prompt=None,
    prompt_cache_key=None,
    reasoning=Reasoning(effort="medium", generate_summary=None, summary=None),
    safety_identifier=None,
    service_tier="default",
    status="completed",
    text=ResponseTextConfig(format=ResponseFormatText(type="text"), verbosity="medium"),
    top_logprobs=0,
    truncation="disabled",
    usage=ResponseUsage(
        input_tokens=762,
        input_tokens_details=InputTokensDetails(cached_tokens=0),
        output_tokens=1090,
        output_tokens_details=OutputTokensDetails(reasoning_tokens=640),
        total_tokens=1852,
    ),
    user=None,
    billing={"payer": "developer"},
    prompt_cache_retention=None,
    store=True,
)
