export const IMAGE_NODE_HEADER_HEIGHT = 36;
export const IMAGE_NODE_MIN_CONTENT_HEIGHT = 144;
export const IMAGE_NODE_MIN_WIDTH = 180;
export const IMAGE_NODE_MIN_HEIGHT = IMAGE_NODE_HEADER_HEIGHT + IMAGE_NODE_MIN_CONTENT_HEIGHT;
export const IMAGE_NODE_MAX_CONTENT_WIDTH = 720;
export const IMAGE_NODE_MAX_CONTENT_HEIGHT = 540;

export const SIMULATION_BOX_MIN_WIDTH = 240;
export const SIMULATION_BOX_MIN_HEIGHT = 200;
export const SIMULATION_BOX_DEFAULT_WIDTH = 420;
export const SIMULATION_BOX_DEFAULT_HEIGHT = 280;
