name: ci

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
          POSTGRES_DB: app
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U app" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
      - name: Frontend install & lint
        working-directory: frontend
        run: |
          pnpm install
          pnpm lint
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        env:
          UV_INSTALL_DIR: ${{ runner.temp }}/uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "${{ runner.temp }}/uv/bin" >> $GITHUB_PATH
      - name: Backend install & tests
        working-directory: backend
        run: |
          uv sync --dev
          uv run pytest -q
